builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Target={{.Env.GOOS}}/{{.Env.GOARCH}}

archives:
  - replacements:
      darwin: macOS
    format_overrides:
      - goos: windows
        format: zip

release:
  draft: true

changelog:
  sort: asc

brews:
  - tap:
      owner: junk1tm
      name: homebrew-tap
      branch: main
      token: {{.Env.HOMEBREW_TAP_GITHUB_TOKEN}}
    homepage: https://github.com/junk1tm/nextver
    description: A dead simple CLI tool that prints the next semantic version based on the last tag of your git repository
    license: MIT
