builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Target={{.Env.GOOS}}/{{.Env.GOARCH}}

archives:
  - replacements:
      darwin: macOS
    format_overrides:
      - goos: windows
        format: zip

release:
  draft: true

changelog:
  sort: asc
